# Generated by Django 5.2.5 on 2025-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringapp', '0002_group_groupmessage_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
